### ISSUE TITLE
Rotating the phone does not rotate the image in ios

### ISSUE THREAD

**Issue by halaharr** [NordlingArt/nativescript-na-camera#4]
Hi,
     Is it possible to rotate the live image when the phone is rotated. When I rotate the camera to landscape the image does not rotate accordingly

thanks

**Comment by NordlingArt** [comment]
Hi. You are right. I haven't taken landscape orientation into account. I will have a look at this. An update will become available once the official release of 3.0 is out.

Thanks for reporting this!

**Comment by NordlingArt** [comment]
@halaharr - This issue has now been fixed under the TNS3 branch. As soon as {N} 3.0 has been released, I will update the master branch and npm.
